### ISSUE TITLE
1주차 과제 - 유튜브 클로닝 코드리뷰

### ISSUE THREAD

**Issue by SeongIkKim** [SeongIkKim/Jasmine#1]
수경 / 승재 코드리뷰 작성바람!

**Comment by SeongIkKim** [comment]
https://github.com/SeongIkKim/Jasmine/blob/2d8ac9b131595b94802d9f98c7beb26ddfafdeb2/week_1(03.07)/assignment_YoutubeClone/index.html#L1-L792

**Comment by SeongIkKim** [comment]
https://github.com/SeongIkKim/Jasmine/blob/2d8ac9b131595b94802d9f98c7beb26ddfafdeb2/week_1(03.07)/assignment_YoutubeClone/styles.css#L1-L393

**Comment by Lee-Su-gyeong** [comment]
.sideBar { 
     background-color: var(--sideBarColor); 
     width: var(--sideBarWidth); 
     overflow: scroll; 
 } 
//overflow: scroll; 했는데도 scroll이 없는 것 같은데 height값(height 값을 전체에서 header 높이 뺀 값)을 주면 생긴다고 합니다.

성익님은 영상 썸네일 img 적용할때 div에 img태그를 추가하셨네요?
저는 div자체에 백그라운드 이미지를 넣어서 이미지 사이즈를 contain으로 써줬습니다.
훨씬 간편한 것 같군요..

저는 sidemenu 부분 fixed을 못해서 어떻게 했나 보고싶었는데 성익님도 안했군요?

오 미디어쿼리 저에 비해 엄청 간단간단하게 짰네..보고 배우겠습니다.
grid-template-columns: repeat(3 , minmax(250px, 1fr)); 
아.. 난 repeatd에 minmax깜빡하고 안썼는데 기억을 해둬야겠군...

총평:
보기 쉽게 코드를 잘짜놔서 코드 읽기가 수월 했습니다.
또한, 미디어쿼리도 핵심적인 것만 딱딱 적용해놓아 나중에 보고 응용하기 좋을 것 같습니다.
과제를 미루지 않고 제때 하는 성익님 존경합니다 파이어~~~~
